"""dev_iot_device_info / dev_only_iot_device_info[_v2] — MQTT credentials.

The second of the two handlers that may CREATE a registry entry (the other is
signup): a device that was provisioned before this server existed asks for its
credentials without ever signing up again, and answering "unknown device" would
leave it with no way to reach the broker.

LOCAL PATCH (homelab): with PETKIT_LOCAL_ESP32_ALIYUN_HOST set, ESP32-class
devices (`not device.is_next_gen` — our Pura Max/T4) are handed
`Device.aliyun_mqtt_host` (`<product key>.iot-as-mqtt.eu-central-1.aliyuncs.com`)
as their mqttHost instead of this server's own address. Linux devices are
untouched: they connect fine with the derived host and their `cacert` trust
store is pinned to it.

Why: handed a bare IP, our T4 completes the TLS handshake to the broker and
then sends nothing at all — no CONNECT, not one byte — and closes on its own
timer, after which it re-runs the whole HTTP init cycle. Captured here
repeatedly, and matching upstream alex-so-3/petkit-local#33 and #34 and the
same finding on a D4S in PineappleEmperor's fork (commit a51c164, "let a
device dial the broker by its Aliyun name"). A completed handshake rules out
cipher, version and certificate parsing, which leaves the certificate's
identity: our cert's CN and DNS SANs said `petkit-local`, and embedded mbedtls
builds commonly match only CN and DNS SANs and never implement IP-SAN
matching, so dialling by IP can never match.

Two things outside this file make it work, and it is useless without them:
  * DNS: `address=/iot-as-mqtt.eu-central-1.aliyuncs.com/<this host>` on both
    Pi-holes (workloads/homelab/pihole-lists.hcl), so the name resolves here
    rather than to Alibaba.
  * The broker certificate must carry `*.iot-as-mqtt.eu-central-1.aliyuncs.com`
    as a DNS SAN. `ensure_self_signed` never re-issues an existing cert, so
    ours was generated by hand into /data/certs.

Remove all three once upstream ships #34's proposed `mqtt_host_override`.
"""
from __future__ import annotations

import logging
import os
from urllib.parse import urlparse

from aiohttp import web

from petkit_local.devices import payloads
from petkit_local.devices.base import Device
from petkit_local.http.handlers._common import (
    device_id, device_serial, no_device_response, request_device,
)

log = logging.getLogger(__name__)


def self_mqtt_host(config: dict) -> str:
    """Return the broker hostname to hand devices — the box they already reach.

    Derived from the configured `api_url`, not from the request's Host header:
    the device opens a separate MQTT connection, so the value has to be an
    address it can reach on its own.

    Takes the config rather than the request because proxy mode's redaction
    policy needs the same answer with no request in hand, and the two must not
    be able to disagree: redaction rewrites the upstream cloud's broker address
    to whatever this returns, so a second derivation that drifted would hand a
    device an address it is not listening on.

    Returns:
        The hostname, or "" when `api_url` has none to give. Empty is a working
        outcome, not a failure — the device then falls back to the HTTP
        heartbeat, which is slower but needs no broker.
    """
    return urlparse(config.get("api_url", "")).hostname or ""


def _resolve_or_create_device(request: web.Request) -> Device | None:
    """Return the requesting device, registering it if it is unknown.

    Resolution (id, then serial) is the shared one, so an unusable id falls
    back to the serial number and we return the SAME device with its real MQTT
    credentials instead of minting a phantom device with fresh keys. Only if
    that finds nothing AND the request carries a usable id do we create.
    """
    device = request_device(request)
    if device is not None:
        return device

    petkit_id = device_id(request)
    sn = device_serial(request)
    if petkit_id is None:
        log.warning("iot_device_info: no device for id=%s sn=%s (X-Device=%s)",
                    petkit_id, sn, request.get("x_device", {}))
        return None

    registry = request.app["registry"]
    return registry.get_or_create(
        petkit_id=petkit_id,
        device_type=request.get("device_type", "t5"),
        serial_number=sn,
    )


async def handle_iot_device_info(request: web.Request) -> web.Response:
    """`dev_iot_device_info` / `dev_only_iot_device_info[_v2]` — Aliyun-wrapped
    MQTT credentials. All three endpoint names route here (`http/server.py`);
    nothing routes to `handle_iot_device_info_flat` below, despite what its own
    docstring and `payloads.to_iot_device_info_flat`'s imply.

    Returns:
        `payloads.to_iot_device_info()`: the broker host plus the product key,
        device name and secret the device signs its MQTT CONNECT with (see
        `mqtt/auth.py`), nested in the Aliyun IoT envelope every model reads,
        ESP32 included.

    LOCAL PATCH: ESP32-class devices are given the Aliyun name rather than our
    address — see this file's module docstring for why, and for the DNS and
    certificate work it depends on.
    """
    device = _resolve_or_create_device(request)
    if not device:
        return no_device_response()
    esp32 = not device.is_next_gen
    public_host = os.environ.get("PETKIT_LOCAL_PUBLIC_MQTT_HOST", "")
    use_public = bool(public_host) and esp32
    use_aliyun = bool(os.environ.get("PETKIT_LOCAL_ESP32_ALIYUN_HOST")) and esp32 and not use_public

    # A name we own, with a certificate from a CA the stock firmware already
    # trusts. The Aliyun name it would otherwise be handed can only ever carry
    # our self-signed certificate, which that firmware rejects outright
    # (TLS alert 48, unknown_ca - measured, 15 attempts per boot).
    if use_public:
        mqtt_host = public_host
    elif use_aliyun:
        mqtt_host = device.aliyun_mqtt_host
    else:
        mqtt_host = device.resolve_mqtt_host(self_mqtt_host(request.app["config"]))

    # LOCAL PATCH: ESP32 devices get the FLAT block. `payloads` says an
    # `ali`-wrapped reply "leaves ESP32 devices unable to read their MQTT
    # credentials at all", and `http/server.py` routes all three endpoint names
    # to this handler, so upstream's flat builder is never reached and every
    # device gets the wrapped shape. Our T4 runs its whole init over HTTP and
    # then never opens an MQTT connection at all, which is what being unable to
    # read those credentials looks like from here.
    body = (payloads.to_iot_device_info_flat(device, mqtt_host) if esp32
            else payloads.to_iot_device_info(device, mqtt_host))

    log.info("IoT device info: id=%d -> pk=%s dn=%s mqttHost=%s%s%s",
             device.petkit_id, device.mqtt_product_key, device.mqtt_device_name, mqtt_host,
             " [local patch: public host]" if use_public else (
                 " [local patch: aliyun name]" if use_aliyun else ""),
             " [local patch: flat]" if esp32 else "")
    return web.json_response(body)


async def handle_iot_device_info_flat(request: web.Request) -> web.Response:
    """Dead code: not routed anywhere in `http/server.py`. Left as upstream has
    it, unpatched — see `handle_iot_device_info`.
    """
    device = _resolve_or_create_device(request)
    if not device:
        return no_device_response()
    mqtt_host = device.resolve_mqtt_host(self_mqtt_host(request.app["config"]))
    log.info("IoT device info (flat): id=%d -> pk=%s dn=%s mqttHost=%s",
             device.petkit_id, device.mqtt_product_key, device.mqtt_device_name, mqtt_host)
    return web.json_response(payloads.to_iot_device_info_flat(device, mqtt_host))
